import { Game } from '../types/games';

export const AVAILABLE_GAMES: Game[] = [
  {
    id: 'spin-wheel',
    name: 'Spin to Win',
    description: 'Spin the colorful wheel and win up to 10,000 CKB!',
    icon: '🎡',
    minBet: 100,
    maxBet: 1000,
    category: 'classic',
    difficulty: 'easy',
    rtp: 95,
    isPopular: true,
  },
  {
    id: 'dice-roll',
    name: 'CKB Dice',
    description: 'Roll the dice and predict your luck! Win 2x your bet on correct guess.',
    icon: '🎲',
    minBet: 50,
    maxBet: 500,
    category: 'luck',
    difficulty: 'easy',
    rtp: 97,
    isNew: true,
  },
  {
    id: 'coin-flip',
    name: 'Coin Flip',
    description: 'Classic 50/50 coin flip. Double your CKB on correct guess!',
    icon: '🪙',
    minBet: 25,
    maxBet: 1000,
    category: 'luck',
    difficulty: 'easy',
    rtp: 98,
    isPopular: true,
  },
  {
    id: 'number-guess',
    name: 'Number Guess',
    description: 'Guess the number 1-10. Higher risk, higher rewards!',
    icon: '🔢',
    minBet: 75,
    maxBet: 750,
    category: 'luck',
    difficulty: 'medium',
    rtp: 90,
  },
  {
    id: 'endless-runner',
    name: 'CKB Dino Run',
    description: 'Chrome Dino style endless runner! Survive to win CKB rewards. 200 CKB entry fee.',
    icon: '🦖',
    thumbnail: '/games/dino-thumbnail.svg',
    minBet: 200,
    maxBet: 200,
    category: 'skill',
    difficulty: 'medium',
    rtp: 95,
    isNew: true,
    isPopular: true,
  },
];

export const GAME_CATEGORIES = [
  { id: 'all', name: 'All Games', icon: '🎮' },
  { id: 'classic', name: 'Classic', icon: '🎰' },
  { id: 'luck', name: 'Luck Games', icon: '🍀' },
  { id: 'card', name: 'Card Games', icon: '🃏' },
  { id: 'skill', name: 'Skill Games', icon: '🎯' },
] as const;
